// Generated by scripts/generate-godot-pwa.mjs. Do not edit.
'use strict';
const CACHE_PREFIX = 'manman-island-';
const CACHE_NAME = CACHE_PREFIX + "0abaafde00557b8240c4";
const PRECACHE_URLS = [
  "./index.html",
  "./index.js?build=84765261a329864a",
  "./boot-manifest.json",
  "./content-manifest.json",
  "./manifest.webmanifest",
  "./pwa/icon-192.b3a22addd3acddb8.png",
  "./pwa/icon-512.91db8df9c60a342c.png",
  "./loading/dock-a9a4fd579d445666.webp",
  "./loading/courtyard-eabbfa22e27161d1.webp",
  "./loading/sunset-c510303588ed8123.webp",
  "./loading/island-ec14a187120b2cbb.webp",
  "./index.audio.worklet.js",
  "./index.audio.position.worklet.js",
  "./index.png",
  "./index.icon.png",
  "./index.apple-touch-icon.png",
  "./audio/instruments/morning.wav",
  "./audio/instruments/breeze.wav",
  "./audio/instruments/quiet.wav",
  "./index.wasm.gzip.068f0afee25cb00241c3360e5456388a4dd9ed781f9fd742c132983d6f525006",
  "./index.pck.gzip.a12f922e6e94e3d40190137b44d5e6ef11e832a05f0960f793391a62e0020e74",
  "./content-067dd28472c89042ca5292a9edea0be36ca95abde0612010b58eb1b7cd45ea4a.pck.gzip",
  "./content-3c36f7527955c4dad889bcc82241e7a8eefebac270e19f7757992c7d130bab80.pck.gzip",
  "./content-bcbc04fb014cf6c79e82c74dd4ea2d740f58a9d1702b54e844ca3664ec8ddead.pck.gzip",
  "./content-4e50ab76bb4c104da383962492ff1047a99a92d87ff31c12bb66195a3e1ad830.pck.gzip",
  "./content-ba9e26f37b02d6e10fae4886a3562b92e8f0b0017051c0e81f64d0af3e8988fc.pck.gzip",
  "./content-daea1ffa922cae5188b444df6b6284e896e338e640cf8c2b48e4418d2e9f3fea.pck.gzip",
  "./content-d312e7d53dd4e6f608a8651edaad16f3d322cda6f59e2118946f154f43aca232.pck.gzip",
  "./content-87d057ea8b99fd5305d4b1ef001f69738651caab6561e01382338b124ae0e850.pck.gzip",
  "./content-8ec34efe6c664326b0086166e17087797d30ec1d2d5bf10f56142884179b6c7f.pck.gzip",
  "./content-bfa8ae7bb75adec7fa2ca3d815b09fd591028bdf2d522d91900d2d66357660c4.pck.gzip",
  "./content-c6f6ad2d368b5999d241a2d913224bf118e2a3b61a56191b3f8e5bd1c90b8dee.pck.gzip"
];
const OPTIONAL_PACK_URLS = [
  "./content-401d50c84acc23b49e3254fe4cdf3088d1ad93744b78dd9f4c6347f4c81abac8.pck.gzip",
  "./content-53977280286420beecf461be81763220350e41a3e9f58060015ffbf4892e74c2.pck.gzip",
  "./content-967cb598307149ba1f004c026306b3e0a13d2d191e0abd1656b7c8083aecbe43.pck.gzip",
  "./content-48d4db522de4404133d6991c40c41235e60a833094c1ab63827f6ec210f5cf33.pck.gzip",
  "./content-ccdedc693e348142e3416783ebda1ee4c5d32297778b528829c38491dc7b7a50.pck.gzip",
  "./content-e42388ae1f981eddf9540ce367b4c667c8d66b72c1bd233a3ef3d5863d488eab.pck.gzip",
  "./content-0008192dd47d726d1b5d081ade2c6f9b92987f8ceacea7ac348f395926cb802e.pck.gzip",
  "./content-0e82b83aba40cc783d4bcf9a15d01fca722e5994e866316c5f98a26a5a24cc33.pck.gzip",
  "./content-77d6fffd645378acb8a325eb09c2f80137e55efaa0f66302948229e571c95d78.pck.gzip",
  "./content-f52ce29429a8b898879e2bfe6cb47973da18bb7ab89def7f98d7272d26fa6639.pck.gzip",
  "./content-d7186d9d6d37d263fd87978ff832c77375100eace271dd53a87a89da6cb4467d.pck.gzip",
  "./content-0dfbafa9a62f1dc7527d27bd61d55debea93b42260e543f3e0f3cffa4b3e59f8.pck.gzip",
  "./content-75a54c83b0e7404b012dacfbd055794c03d95f5dd0b24c3acb800865576696d4.pck.gzip",
  "./content-ba82503caa1221b144a38dff63b5bfe89bb2ebad2b3ef3bedbc90d85b22eca3e.pck.gzip",
  "./content-70f1676241041b5b4670e3fdabd155d93af529dbfbe7f15e713cf70eb0313015.pck.gzip",
  "./content-9c64a258ef4aabf583a70794945d02b695057d5f95171762f43fad15cf915ec1.pck.gzip",
  "./content-e63109b6f093e489872e9c3f97074848efbc2c46f527043c4a48c552769cda73.pck.gzip",
  "./content-199434894e9e2623cef3b27fcc6d8ff34ff51e39f313aded66c60d26df700836.pck.gzip",
  "./content-2cca827502e92d2a0969169684c93fd8c9259577e7db8e6ed24d258c7bdd2e09.pck.gzip",
  "./content-d67902f50aa7cf6d034693ebdd395da20ac4f78c8238837b65d59196f5059759.pck.gzip",
  "./content-6b8c84ae462b449e29e1be7ceb4414840e603828d3397df6d4bef4e796d17fe0.pck.gzip",
  "./content-0c151a7a85854720607589af8c8d1ede81aa7720238beab28ad6385585db92b3.pck.gzip",
  "./content-5786d04e2ccd29d372fe833751b8612146ce8f13b0d1f05fcf0999c0c2a0b4d8.pck.gzip",
  "./content-01bf3dc05c6f0bd7a8d3eba8513e6f0019f86cff2735c8ff0e399264e9e38bc2.pck.gzip",
  "./content-1399192f9cc6c408583e69dc0f228629aae70451dce4f847e7348452de9c3555.pck.gzip",
  "./content-e0a2a2a14b78a72f0a039056ad3ee1db02c33b04ceb5c5b46d1263e873bfd05b.pck.gzip",
  "./content-c27157e651a774230ddc7c04254ba55db29c94785ac7d6e9232c4f6189140621.pck.gzip"
];
const scopeUrl = (value) => new URL(value, self.registration.scope).href;
const precache = new Set(PRECACHE_URLS.map(scopeUrl));
const optionalPacks = new Set(OPTIONAL_PACK_URLS.map(scopeUrl));
const shellUrl = scopeUrl('./index.html');

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    // Keep large Godot artifacts sequential so installation has bounded memory.
    for (const url of PRECACHE_URLS) await cache.add(url);
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME).map((key) => caches.delete(key)));
    await self.clients.claim();
  })());
});

async function cacheFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok && response.type !== 'opaque') await cache.put(request, response.clone());
  return response;
}

async function navigation(request) {
  try {
    const response = await fetch(request);
    if (response.ok && response.type !== 'opaque') {
      const cache = await caches.open(CACHE_NAME);
      await cache.put(shellUrl, response.clone());
    }
    return response;
  } catch (error) {
    const cached = await caches.match(shellUrl);
    if (cached) return cached;
    throw error;
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith(navigation(request));
    return;
  }
  // This strict allowlist excludes APIs and all save/IndexedDB data. Optional
  // content enters Cache Storage only after the game actually requests it.
  if (precache.has(url.href) || optionalPacks.has(url.href)) event.respondWith(cacheFirst(request));
});
