// Generated by scripts/generate-godot-pwa.mjs. Do not edit.
'use strict';
const CACHE_PREFIX = 'manman-island-';
const CACHE_NAME = CACHE_PREFIX + "3d46df901c02310da8a3";
const PRECACHE_URLS = [
  "./index.html",
  "./index.js?build=e897da1506a44527",
  "./boot-manifest.json",
  "./content-manifest.json",
  "./manifest.webmanifest",
  "./pwa/icon-192.b3a22addd3acddb8.png",
  "./pwa/icon-512.91db8df9c60a342c.png",
  "./loading/dock-a9a4fd579d445666.webp",
  "./loading/courtyard-eabbfa22e27161d1.webp",
  "./loading/sunset-c510303588ed8123.webp",
  "./loading/island-ec14a187120b2cbb.webp",
  "./index.audio.worklet.js",
  "./index.audio.position.worklet.js",
  "./index.png",
  "./index.icon.png",
  "./index.apple-touch-icon.png",
  "./audio/instruments/morning.wav",
  "./audio/instruments/breeze.wav",
  "./audio/instruments/quiet.wav",
  "./index.wasm.gzip.bc907a55c96a6362427aee152ab5cf4e19882ce5c49eb869de3c713d13997997",
  "./index.pck.gzip.0e331b4d301b78e2e5cb9360866b017e363e1a1ef654da28b4982556228c205c",
  "./content-f2f5eab7dc5f37850132c6863800a690734615b71022ebec4950a485bd870708.pck.gzip",
  "./content-04fde674dea4eaa20082af2a892f8e6c9fb12c2d78b97472ee5e5119aff9fb5f.pck.gzip",
  "./content-790bfe5df474d17ecd73f951c1018a0300b701d8d15ef1a0a0225f6720e9d1fb.pck.gzip",
  "./content-99149be6cccfc8e7010d60fac9c8a575607f700629fba229649f3b67604e0ca7.pck.gzip",
  "./content-963ed9640802ea81cf4fc4fa1de80716296215acc5e7f6e47e6244b550c6e866.pck.gzip",
  "./content-41452e4514d28485349120882e644506859edc76c34dbd0793c328e12d340821.pck.gzip",
  "./content-4ad372655f206f78d478d2e8437b5c3eae7c913d5af31dd8ac20a230b90f65d0.pck.gzip",
  "./content-d117f1d7dbdd5fdaacb489a02eb9ade23e3b04664e398ce344b25084e0d2b07d.pck.gzip",
  "./content-164e4492b90c358df6c9374c0e1469cff978e12a5603420aca6f2a0c51ca8a67.pck.gzip",
  "./content-b71df371c1ce80bb3cb0abe53026f08eb13db329e1e3900094d804d5a194a715.pck.gzip",
  "./content-c68db2b8598be3960c0764f52fb122ee5d652591c96a69f490b4270c5d2e5072.pck.gzip",
  "./content-fd2b81b078aaf67563d13c0d331ecb13cf5f576b9179810343589cb2de82891f.pck.gzip",
  "./content-977ef2ba848b286248d8491d78856330be71d2f6693766bf4e635f82f7083d23.pck.gzip",
  "./content-dfda61a3ef36d99a715d7af9404275192d4746560a2c6c8d1b5fd679e47775da.pck.gzip"
];
const OPTIONAL_PACK_URLS = [
  "./content-8f905360e1f12645cf773d28eecb661d90a2353aa6ec42f4008ae3c511c33134.pck.gzip",
  "./content-b79edb04f5a95521e790144c440a28078816bca4fe7255938b5f4dc064dfad4d.pck.gzip",
  "./content-926b71af8e146ed134ebcba7901c0d236f5fe035ade9a421ba6ddafe53f629d0.pck.gzip",
  "./content-9f627d48f09e204ea340d7e007193bd5e608f4af65aca6ee751369f205355893.pck.gzip",
  "./content-a35503b053426bce37de667f137e2d2778cbd051da2447561bb2d861345d4d6d.pck.gzip",
  "./content-efcf07200a41be079efcc337a6710e9c86242ba59670e0b081cf54c350f2331e.pck.gzip",
  "./content-57933786197500718e4a0b75896d2dd7f4e555d9725f09f2dac118c9e379ba47.pck.gzip",
  "./content-4f1140da118fb74651d6ed0838a87bba49412ea36ccc701b7d645f6defcf07a1.pck.gzip",
  "./content-704b264110c74204e77e3664c8f58e5e8e18f033de8f83985e8bd696438f3dd1.pck.gzip",
  "./content-f933e9ee2e1f327320c334174851d8fb0bc3b255ff7e02521d8c741bec676710.pck.gzip",
  "./content-fd553fe55a2d00fe1bf88d44bb331064bd701581a0a0ddca4c62db9be211b66d.pck.gzip",
  "./content-c7c42c5c0aaa56eab44fd02ca560282645df27a2fbbb7f466aedcc9426a2a556.pck.gzip",
  "./content-817eb412c0676a8962cd35e3e34296f66617677069fd2df0376345fc52e8f0f7.pck.gzip",
  "./content-956a923ca5924790a09c43147e2d838905f338c1b8d0bdcb808777282b85e87f.pck.gzip",
  "./content-060345ef25348ed587b675a0df2f0a3d68e013fc146775ba04c4ecbf6cf52d98.pck.gzip",
  "./content-e84b1e3f4d01fc95ba479497fabdbc092fde65f47804950dc70b5889c32646de.pck.gzip",
  "./content-b79a0cd8e4c7f3bd6e6bb974fcf15dc057a62959b18356e80ebf030230e5753d.pck.gzip",
  "./content-757bdb35e57eb9f1dbf2e65d29d0b8cd167c1a7c1e5ed787192d0c0311f08bef.pck.gzip",
  "./content-6487b359b0bef1ad8faadb05b9ccca931cdea310f154f83ce91000fe940a11c8.pck.gzip",
  "./content-c8bef1f786f4219099e30ce64c1b9b4890bea3bb01aef98be68415dd1de8c09c.pck.gzip",
  "./content-912a450d8707876439bf7d2b50874af7410465a0b3138f9a21808253c03de172.pck.gzip",
  "./content-225eddbfe2fd5321db680deb4d6fba86d22e892e32093b07a67f37537413148d.pck.gzip",
  "./content-b3acdd751515d065542ab6985eb003d583e145ef759a2f5ce8149e1f564daa5b.pck.gzip",
  "./content-7e611da36f31ebe2a6a8bb0e09d157964152d8510ebf316504ea964401357c7e.pck.gzip",
  "./content-b73ecf1488cb84d57ee0dbf4a9f45076e1f3266bb457417e706dcf69fa4e8815.pck.gzip",
  "./content-a1fb040fa26add037b5a98aa312f4ebd0ed36546283921a4807df9f752db8f23.pck.gzip",
  "./content-9952f1faf8450d42efed84ab9cc6e7bac677626839b3e8b7a00f9f502b6dbdd4.pck.gzip",
  "./content-4a0032284453e13d6512ec689dfbb58e0ff92e5399928a8a47077e0f301152f8.pck.gzip",
  "./content-2630d5de5e252a0c45988d1e8f873d3258d84ff471a7ea3faa11c59f8b280bd4.pck.gzip"
];
const scopeUrl = (value) => new URL(value, self.registration.scope).href;
const precache = new Set(PRECACHE_URLS.map(scopeUrl));
const optionalPacks = new Set(OPTIONAL_PACK_URLS.map(scopeUrl));
const shellUrl = scopeUrl('./index.html');

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    // Keep large Godot artifacts sequential so installation has bounded memory.
    for (const url of PRECACHE_URLS) await cache.add(url);
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME).map((key) => caches.delete(key)));
    await self.clients.claim();
  })());
});

async function cacheFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok && response.type !== 'opaque') await cache.put(request, response.clone());
  return response;
}

async function navigation(request) {
  try {
    const response = await fetch(request);
    if (response.ok && response.type !== 'opaque') {
      const cache = await caches.open(CACHE_NAME);
      await cache.put(shellUrl, response.clone());
    }
    return response;
  } catch (error) {
    const cached = await caches.match(shellUrl);
    if (cached) return cached;
    throw error;
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith(navigation(request));
    return;
  }
  // This strict allowlist excludes APIs and all save/IndexedDB data. Optional
  // content enters Cache Storage only after the game actually requests it.
  if (precache.has(url.href) || optionalPacks.has(url.href)) event.respondWith(cacheFirst(request));
});
