// Generated by scripts/generate-godot-pwa.mjs. Do not edit.
'use strict';
const CACHE_PREFIX = 'manman-island-';
const CACHE_NAME = CACHE_PREFIX + "86c00b2c7d5c25e4563f";
const PRECACHE_URLS = [
  "./index.html",
  "./index.js?build=773893349559bd67",
  "./boot-manifest.json",
  "./content-manifest.json",
  "./manifest.webmanifest",
  "./pwa/icon-192.b3a22addd3acddb8.png",
  "./pwa/icon-512.91db8df9c60a342c.png",
  "./loading/dock-a9a4fd579d445666.webp",
  "./loading/courtyard-eabbfa22e27161d1.webp",
  "./loading/sunset-c510303588ed8123.webp",
  "./loading/island-ec14a187120b2cbb.webp",
  "./index.audio.worklet.js",
  "./index.audio.position.worklet.js",
  "./index.png",
  "./index.icon.png",
  "./index.apple-touch-icon.png",
  "./audio/instruments/morning.wav",
  "./audio/instruments/breeze.wav",
  "./audio/instruments/quiet.wav",
  "./index.wasm.gzip.068f0afee25cb00241c3360e5456388a4dd9ed781f9fd742c132983d6f525006",
  "./index.pck.gzip.0.e624d85677a7dc8039b42a85c8ced9c409c074038ebeeda96b637dce98ef10d8",
  "./index.pck.gzip.1.979f802cd94c46a2c46e2ef0cc28d55545b960476e4a4c662753cbea5d3fdfe6",
  "./content-549329b8bc06af97fe94aee19ba19539b855c3aab8e77722678ad281fd64d874.pck.gzip",
  "./content-a82e386f00df0e9e4748235f0572fa47c693d34e7a84ac0efa0cde2c8dde7c2a.pck.gzip",
  "./content-8a286218cabd544f56658fe56115d9b7d67b2a67cbdebed41fc1c438e8fcaec5.pck.gzip",
  "./content-8e0fa12f59073060ece0128708bd20da0da9dd5267e335a3de1d3528e658ae70.pck.gzip",
  "./content-573e3f28ecfe92b64a21df5eb792a230bd7fc02ed2f363813487c36519362a8e.pck.gzip",
  "./content-922f42052cc8dabb1953cb8b06499be72c3f042f397f3074046213df2bf0e304.pck.gzip",
  "./content-820480cf7cfdafceecbc69394cd63d06f0aab135265bc0a8e8f18765a16b81f0.pck.gzip",
  "./content-595adc5f4fe41d6837301cdc181e0e5fa6154df62b105c2f5b873214710eea95.pck.gzip",
  "./content-e1a6b97d652cf1549375f0d6d8173515e092afab69945eee65463d5d43d67e25.pck.gzip",
  "./content-08d593e396becfb08b1d4fcf7b17590c1108f597dbfce9b9d787f37529512d82.pck.gzip",
  "./content-063a58a0e2baad3d460822a8f07f515605c310e6c357f85c58fba9945f6ebcb1.pck.gzip",
  "./content-f2b05d21651b8a082253b8ab9689aae855cfea3f1986862fc5882852fda5dc0d.pck.gzip",
  "./content-de7b564d7c8fe6a36396d4e653171f1a02ff53213963c48ef7745ce6138eaa2a.pck.gzip",
  "./content-4aca30a8251417225067c8b86e2d4b087221458be986eac5a18fc1190e29ea7c.pck.gzip"
];
const OPTIONAL_PACK_URLS = [
  "./content-401d50c84acc23b49e3254fe4cdf3088d1ad93744b78dd9f4c6347f4c81abac8.pck.gzip",
  "./content-53977280286420beecf461be81763220350e41a3e9f58060015ffbf4892e74c2.pck.gzip",
  "./content-50f8c77c7e807ab857431367c352b7b874fd3495722c952296610baff5facea5.pck.gzip",
  "./content-a532dbd3aece5b164d39adef50751e58dd8ce81f5c875e9c1ce7e6c98f0c1e44.pck.gzip",
  "./content-a41a548507c9131a411468db953fa28055658f67a2db275e9df81fae833c4dac.pck.gzip",
  "./content-6a9641a5aa4c2325870ac9767ec7f9d9248c32303e500c9abaec2b5b555156f1.pck.gzip",
  "./content-e3c9f5e8ade2e7beb2ba7aa60359c6f6628214e7e9d21273b614db4e6edfb131.pck.gzip",
  "./content-f93c0acf2eeaaffffc2e9d6fafe662b9724aeac158a1a6a8bd99deae77ffbc86.pck.gzip",
  "./content-49645f6f1dc30ae0c44d7a63c5cbd71e40a1d214106a0563e7de53faa6b6f5c0.pck.gzip",
  "./content-580792a1216c6db6727c35d520924b99da5507a2bff45f652c8c87e7a4a7dcaf.pck.gzip",
  "./content-5d4cea73313a9ba176e7bbc8083a5b4dbcae10612504a151aa2172e81cbd2684.pck.gzip",
  "./content-84bff7e05d1efb4d28eac6dad7389cb1d877ae42dfd2b6e1983d63cab7b939a9.pck.gzip",
  "./content-75a54c83b0e7404b012dacfbd055794c03d95f5dd0b24c3acb800865576696d4.pck.gzip",
  "./content-82a94b28c0aa193dbe27eb4885a8052f0b1427d8fbadd02fa34bf0894692bb26.pck.gzip",
  "./content-b788fce1ab8ecd3be1884a881970096f390485706e56072ab368de2536ca0252.pck.gzip",
  "./content-af9e93b7377ffdb902ea5306093401ceee9cd927190cd9b08e5643b3833f390d.pck.gzip",
  "./content-46498a31579d750435f399934750a7841bbe61d3d9d5ed0e6bbe52c44f843030.pck.gzip",
  "./content-154deedc0c257da588b22d80cf7e4ac3e0a9e4f6213670254f7ccd47c846a70b.pck.gzip",
  "./content-5b2cc05badb4b38524142e2b300037686c4319639fca29ee41830b895f939c7a.pck.gzip",
  "./content-f24cfc63c50c5c586afac7c32089400ea9f75810724d4a566a7a3759f565a16e.pck.gzip",
  "./content-6b8c84ae462b449e29e1be7ceb4414840e603828d3397df6d4bef4e796d17fe0.pck.gzip",
  "./content-e23fbe220f9c0defd396c37736d7e5801d58db784ae4be7af5e69008f098c692.pck.gzip",
  "./content-96759125264109990e8a5d1f20bbc7c6626e4d2fbf98f8f7837b21993adaa564.pck.gzip",
  "./content-ab608678c344e347d70b50f0b87eb03800e6c862e33f0b55d3bce6589992e2f9.pck.gzip",
  "./content-ef74fe3467d3eb33726cf1ca1b4520eeae8153603b40ed8795af7382cb94df4d.pck.gzip",
  "./content-610faa889a3004d520a37001df31756239b1087b6ff6b189103ca097ef78e386.pck.gzip",
  "./content-806ec3dc565a396e81db5d7511d2700b013ca1ba1ae81c6a3307c59f93964f12.pck.gzip"
];
const scopeUrl = (value) => new URL(value, self.registration.scope).href;
const precache = new Set(PRECACHE_URLS.map(scopeUrl));
const optionalPacks = new Set(OPTIONAL_PACK_URLS.map(scopeUrl));
const shellUrl = scopeUrl('./index.html');

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    // Keep large Godot artifacts sequential so installation has bounded memory.
    for (const url of PRECACHE_URLS) await cache.add(url);
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME).map((key) => caches.delete(key)));
    await self.clients.claim();
  })());
});

async function cacheFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok && response.type !== 'opaque') await cache.put(request, response.clone());
  return response;
}

async function navigation(request) {
  try {
    const response = await fetch(request);
    if (response.ok && response.type !== 'opaque') {
      const cache = await caches.open(CACHE_NAME);
      await cache.put(shellUrl, response.clone());
    }
    return response;
  } catch (error) {
    const cached = await caches.match(shellUrl);
    if (cached) return cached;
    throw error;
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith(navigation(request));
    return;
  }
  // This strict allowlist excludes APIs and all save/IndexedDB data. Optional
  // content enters Cache Storage only after the game actually requests it.
  if (precache.has(url.href) || optionalPacks.has(url.href)) event.respondWith(cacheFirst(request));
});
